inaka/apns4erl

src/apns.erl
=> Increase APNS max payload up to 2 kylobytes

CHANGELOG.md, src/apns.app.src
=> [#55] 1.0.5 Version Bump

src/apns_connection.erl
This avoids old code reference issues when doing release upgrades.
=> Support {M,F} callbacks as well as funs for feedback/error_fun.

CHANGELOG.md, src/apns.app.src, src/apns.erl
=> Version Bump 1.0.6

include/apns.hrl, src/apns.erl, src/apns_connection.erl
=> Expose extra configuration options for SSL connection

include/apns.hrl, src/apns_connection.erl
Added the ability to specify a fun for error and info logging. Also added the connection name to current logs to Identify connection in a system with multiple ones.
=> Log clarification

rebar.config
=> Fix compile error using gcc 5.2

Makefile, rebar.config
=> Fix sync to use rustyio/sync instead of non-existing inaka/sync

src/apns.erl, src/apns_connection.erl
just look like  apns:connect(Name, ErrorFun, FeedbackFun)
=> support apns:connect(ErrorFun, FeedbackFun)

Readme.md
The previous link doesn't work
=> Update link to .pem generation script

rebar.config
Removed extra dependency in the face of `rustyio/sync`
=> removed extra deps

rebar.config, rebar.lock, src/apns.app.src, src/apns.erl, src/apns_app.erl, src/apns_connection.erl, src/apns_connection_sup.erl, src/apns_sup.erl, test/connection_SUITE.erl, test/test.config
These changes are about to create connections against APNs with Provider Certificates. This is not the final Architecture but it will change when #127 will be implemented. [close #125]
=> [#125] Connecting to APNs with Provider Certificates

README.md, rebar.config
=> [#146] only R19+ supported

src/apns_connection.erl, test/connection_SUITE.erl, test/feedback_SUITE.erl
=> [#148] test coverage to 100%

README.md, src/apns.erl, src/apns_connection.erl
=> [#156] update README file

README.md, elvis.config, src/apns.erl, src/apns_feedback.erl
=> [#167] adding apns:get_feedback/1

README.md, rebar.config, rebar.lock, src/apns.app.src, src/apns.erl, src/apns_connection.erl, test/apns_os_SUITE.erl, test/connection_SUITE.erl
=> [#175] replace gun by chatterbox

CHANGELOG.md, src/apns.app.src
=> [#177] version bump to 2.1.0

README.md, src/apns.erl, src/apns_connection.erl, test/connection_SUITE.erl
=> [#183] create connections without name

CHANGELOG.md, src/apns.app.src
=> [#186] Version Bump to 2.1.1

README.md, src/apns.erl, src/apns_connection.erl, test/connection_SUITE.erl
=> [#188] restricting push only for connection's owner process

README.md, examples/apns_pool/README.md, examples/apns_pool/priv/cert2.pem, examples/apns_pool/priv/key2-noenc.pem, examples/apns_pool/rebar.config, examples/apns_pool/rebar.lock, examples/apns_pool/src/apns_pool.app.src, examples/apns_pool/src/apns_pool.erl, examples/apns_pool/src/apns_pool_sup.erl, examples/apns_pool/src/apns_pool_worker.erl
=> [#191] Example with a pool of connections

.travis.yml, README.md, ci
=> [#193] Setting Travis up

CHANGELOG.md, src/apns.app.src
=> [#196] Version Bump to 2.2.0

src/apns_connection.erl
=> send mandatory headers at top

.travis.yml, README.md, rebar.config
=> [#218] integrating with codecov

.gitignore, CHANGELOG.md, src/apns.app.src
=> [#217] Version Bump to 2.3.0

CHANGELOG.md, src/apns.app.src
=> [#227] version bump to 2.3.1
